apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager # Name and namespace here are before any OpenShift modifications
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: capz-manager-bootstrap-credentials
              key: azure_subscription_id
